(global-set-key (kbd "M-g") 'goto-line)
(global-set-key (kbd "M-h") 'jump-to-register)
(global-set-key (kbd "M-j") 'point-to-register)

(global-set-key (kbd "<home>") 'beginning-of-buffer)
(global-set-key (kbd "<end>") 'end-of-buffer)
(global-set-key [f1] 'start-kbd-macro)
(global-set-key [f2] 'kbd-macro-query) 
(global-set-key [f3] 'kmacro-set-counter) 
(global-set-key [f4] 'kmacro-insert-counter) 
(global-set-key [f5] 'end-kbd-macro) 
(global-set-key [f6] 'name-last-kbd-macro)
(global-set-key [f7] 'call-last-kbd-macro)
(global-set-key [f8] 'call-ten-macros)
(global-set-key [f9] 'exit-recursive-edit)
(global-set-key [f10] 'apropos)
(global-set-key [f11] 'describe-key)
(global-set-key [f12] 'eval-defun) ;evals crnt sexp

(global-set-key (kbd "C-c C-c") 'execute-extended-command)
(global-set-key (kbd "C-x C-d") 'bury-buffer)
(global-set-key (kbd "C-o") 'undo)
(global-set-key (kbd "C-,") 'copy-to-register)
(global-set-key (kbd "C-.") 'insert-register)
(global-set-key (kbd "C-'") 'kill-ring-save)
(global-set-key (kbd "C-;") 'delete-horizontal-space)

(defalias 'list-buffers 'ibuffer)

(defun call-ten-macros () 
   (interactive)
   (progn (call-last-kbd-macro)
          (call-last-kbd-macro)
          (call-last-kbd-macro)
          (call-last-kbd-macro)
          (call-last-kbd-macro)
          (call-last-kbd-macro)
          (call-last-kbd-macro)
          (call-last-kbd-macro)
          (call-last-kbd-macro)
          (call-last-kbd-macro)
  ))
